from .facultad_service import FacultadService
from .grado_service import GradoService
from .universidad_service import UniversidadService
from .tipodocumento_service import TipoDocumentoService
from .departamento_service import DepartamentoService
from .alumno_service import AlumnoService
from .especialidad_service import EspecialidadService
from .tipoespecialidad_service import TipoEspecialidadService
