from .facultad_repositorio import FacultadRepository
from .grado_repositorio import GradoRepository
from .universidad_repositorio import UniversidadRepository
from .tipodocumento_repositorio import TipoDocumentoRepository
from .departamento_repositorio import DepartamentoRepository
from .alumno_repositorio import AlumnoRepository
from .especialidad_repositorio import EspecialidadRepository
from .tipoespecialidad_repositorio import TipoEspecialidadRepository
